version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    container_name: zhkh_postgres
    volumes:
      - ~/.pg/pg_data/zhkh_service:/var/lib/postgresql/data
    env_file:
      - ./django/zhkh_service/.env

  django:
    container_name: back_django
    restart: always
    build:
      context: .
      dockerfile: ./django/zhkh_service/Dockerfile
    volumes:
      - ./django/zhkh_service:/zhkh_service
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./django/zhkh_service/.env
    command: python manage.py runserver 0.0.0.0:8000

  react:
    container_name: front_react
    restart: always
    build:
      context: .
      dockerfile: ./react/Dockerfile
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./react:/react
      - /react/node_modules
    ports:
      - "3001:3000"
    expose:
      - 3001

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    env_file:
      - ./django/zhkh_service/.env


  poutiuvbm:
    container_name: sdfgdfytu
    restart: always
    build:
      context: .
      dockerfile: ./django/zhkh_service/docker_chat/Dockerfile
#    command: ./.venv/bin/activate && uvicorn --port 8005 zhkh_service.asgi:application


volumes:
  static_volume:
  media_volume: