# Generated by Django 4.2.16 on 2025-01-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
