# Generated by Django 4.2.16 on 2025-01-26 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_documents_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ratio', models.FloatField(blank=True, max_length=15, verbose_name='Кол-во рублей за ед.')),
                ('key', models.CharField(choices=[('coldWater', 'Холодная вода'), ('hotWater', 'Горячая вода'), ('disposal', 'Водоотведение'), ('electricity', 'Электроэнергия')], max_length=255, verbose_name='Ключ')),
                ('person_count', models.PositiveIntegerField(default=1, verbose_name='Кол-во человек')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='LivingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Адрес')),
                ('number_ls', models.PositiveIntegerField(unique=True, verbose_name='Номер лицевого счета')),
                ('square', models.PositiveIntegerField(verbose_name='Площадь')),
                ('type', models.CharField(choices=[('HABITABLE', 'Жилое'), ('NOT_RESIDENTIAL', 'Не жилое'), ('PARKING', 'Парковочное место')], default='HABITABLE', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жилая площадь',
                'verbose_name_plural': 'Жилые площади',
            },
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_indication', models.FloatField(max_length=55, verbose_name='Последний показатель')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('finish_price', models.FloatField(verbose_name='Итоговая сумма')),
                ('resident_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во прописанных человек')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
            },
        ),
    ]
