# Generated by Django 4.2.16 on 2025-01-26 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_tariff_livingarea_indication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='person_count',
        ),
        migrations.AddField(
            model_name='livingarea',
            name='availability_counters_water',
            field=models.BooleanField(default=False, verbose_name='Наличие счетчиков на воду'),
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.PositiveIntegerField(verbose_name='Норма')),
                ('person_count', models.PositiveIntegerField(default=1, verbose_name='Кол-во человек')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='web.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Норма',
                'verbose_name_plural': 'Нормы',
            },
        ),
    ]
