# Generated by Django 4.2.16 on 2025-01-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_tariff_person_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='summ_above',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма сверх тарифа'),
            preserve_default=False,
        ),
    ]
