# Generated by Django 4.2.16 on 2025-01-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_regulation_summ_above'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indication',
            name='resident_count',
        ),
        migrations.AddField(
            model_name='livingarea',
            name='resident_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во прописанных человек'),
        ),
    ]
