# Generated by Django 4.2.16 on 2025-03-23 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_remove_regulation_summ_without_counters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('file', models.FileField(blank=True, upload_to='appeals/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('IN_WORK', 'В работе'), ('MODERATION', 'На рассмотрении'), ('COMPLETED', 'Выполнено')], default='IN_WORK', max_length=255, verbose_name='Статус')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
