# Generated by Django 4.2.16 on 2025-03-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_regulation_summ_without_counters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения'),
        ),
    ]
