# Generated by Django 4.2.16 on 2025-03-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_livingarea_availability_counters_water_and_more'),
        ('web', '0010_tariff_unit'),
    ]

    operations = [
    ]
