# Generated by Django 4.2.16 on 2025-03-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='appeals/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('IN_WORK', 'В работе'), ('MODERATION', 'На рассмотрении'), ('COMPLETED', 'Выполнено')], default='MODERATION', max_length=255, verbose_name='Статус'),
        ),
    ]
