# Generated by Django 4.2.16 on 2025-03-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_payment'),
        ('web', '0011_merge_20250323_0323'),
    ]

    operations = [
    ]
