# Generated by Django 4.2.16 on 2025-03-25 13:02

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_merge_0010_payment_0011_merge_20250323_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to='receipts/', validators=[web.models.validate_file_extension], verbose_name='Квитанция'),
        ),
    ]
