# Generated by Django 4.2.16 on 2025-04-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_appeal_date_created_alter_appeal_file_and_more'),
        ('web', '0013_alter_receipt_file'),
    ]

    operations = [
    ]
