# Generated by Django 4.2.16 on 2025-04-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_merge_20250405_1235'),
        ('web', '0015_livingarea_tube'),
    ]

    operations = [
    ]
