# Generated by Django 4.2.16 on 2025-04-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_merge_0014_merge_20250405_1235_0015_livingarea_tube'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tube_type', models.CharField(blank=True, choices=[('FIRST', 'Первый водосток'), ('SECOND', 'Второй водосток')], max_length=100, verbose_name='Тип водостока')),
            ],
            options={
                'verbose_name': 'Тип показателя',
                'verbose_name_plural': 'Типы показателей',
            },
        ),
        migrations.AddField(
            model_name='indication',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.indicationtype'),
            preserve_default=False,
        ),
    ]
