# Generated by Django 4.2.16 on 2025-04-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_indicationtype_indication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.CharField(choices=[('DEVELOPER', 'Разработчик'), ('STAFF', 'Администрация')], default='STAFF', max_length=255, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='datadeveloper',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.contact', verbose_name='Контакт'),
            preserve_default=False,
        ),
    ]
