# Generated by Django 4.2.16 on 2025-05-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_indicationtype_indication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livingarea',
            name='home_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
    ]
