# Generated by Django 4.2.16 on 2025-01-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_ls',
        ),
        migrations.RemoveField(
            model_name='user',
            name='square',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
